/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package use_case;

/**
 *
 * @author phfar
 */
public class TelaInicial extends javax.swing.JFrame {
    
    ControladorFarmacia controller;
    
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial(ControladorFarmacia controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoVenda = new javax.swing.JButton();
        botaoCadastrarProduto = new javax.swing.JButton();
        botaoFazerPedido = new javax.swing.JButton();
        botaoEstoque = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Inicial");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1280, 751));
        setResizable(false);

        botaoVenda.setBackground(new java.awt.Color(0, 0, 51));
        botaoVenda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoVenda.setForeground(new java.awt.Color(255, 49, 79));
        botaoVenda.setText("VENDER");
        botaoVenda.setToolTipText("Iniciar uma venda");
        botaoVenda.setPreferredSize(new java.awt.Dimension(250, 250));
        botaoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVendaActionPerformed(evt);
            }
        });

        botaoCadastrarProduto.setBackground(new java.awt.Color(0, 0, 51));
        botaoCadastrarProduto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoCadastrarProduto.setForeground(new java.awt.Color(255, 49, 79));
        botaoCadastrarProduto.setText("CADASTRAR \nPRODUTO");
        botaoCadastrarProduto.setToolTipText("Cadastrar um produto no estoque");
        botaoCadastrarProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoCadastrarProduto.setPreferredSize(new java.awt.Dimension(250, 250));
        botaoCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarProdutoActionPerformed(evt);
            }
        });

        botaoFazerPedido.setBackground(new java.awt.Color(0, 0, 51));
        botaoFazerPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoFazerPedido.setForeground(new java.awt.Color(255, 49, 79));
        botaoFazerPedido.setText("FAZER PEDIDO");
        botaoFazerPedido.setToolTipText("Alterar informações de um produto");
        botaoFazerPedido.setPreferredSize(new java.awt.Dimension(250, 250));
        botaoFazerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFazerPedidoActionPerformed(evt);
            }
        });

        botaoEstoque.setBackground(new java.awt.Color(0, 0, 51));
        botaoEstoque.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoEstoque.setForeground(new java.awt.Color(255, 49, 79));
        botaoEstoque.setText("ESTOQUE");
        botaoEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoFazerPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(529, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoFazerPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(603, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVendaActionPerformed
        this.controller.iniciarTelaVenda();
    }//GEN-LAST:event_botaoVendaActionPerformed

    private void botaoCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarProdutoActionPerformed
        this.controller.iniciarTelaCadastrarProduto();
    }//GEN-LAST:event_botaoCadastrarProdutoActionPerformed

    private void botaoFazerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFazerPedidoActionPerformed
        this.controller.iniciarTelaFazerPedido();
    }//GEN-LAST:event_botaoFazerPedidoActionPerformed

    private void botaoEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEstoqueActionPerformed
        this.controller.iniciarTelaEstoque();
    }//GEN-LAST:event_botaoEstoqueActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrarProduto;
    private javax.swing.JButton botaoEstoque;
    private javax.swing.JButton botaoFazerPedido;
    private javax.swing.JButton botaoVenda;
    // End of variables declaration//GEN-END:variables
}
